# Generated by Django 2.1.1 on 2018-09-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='title_id',
            field=models.UUIDField(unique=True),
        ),
    ]
